"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { browserClient } from "@/app/_lib/supabase-browser";

/**
 * A teacher opens a class of their own: they choose the course, the section
 * number and the term. The teacher is always the signed-in user, and the join
 * code is generated by the database, so neither can be set from here.
 */
export default function NewSectionForm({
  courses,
  teacherId,
  defaultTerm,
  defaultCourseId,
}: {
  courses: { id: string; title: string }[];
  teacherId: string;
  defaultTerm: string;
  defaultCourseId?: string;
}) {
  const router = useRouter();
  const preset = courses.some((c) => c.id === defaultCourseId) ? defaultCourseId : undefined;
  const [courseId, setCourseId] = useState(preset ?? courses[0]?.id ?? "");
  const [number, setNumber] = useState("");
  const [term, setTerm] = useState(defaultTerm);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setBusy(true);
    setError(null);

    const supabase = browserClient();
    const { error: e2 } = await supabase.from("sections").insert({
      course_id: courseId,
      teacher_id: teacherId,
      number: number.trim(),
      term: term.trim(),
    });

    setBusy(false);

    if (e2) {
      setError(
        e2.code === "23505"
          ? "You already have a section with that number for this term."
          : e2.message.includes("row-level security")
          ? "Your account is not allowed to open a class. Ask the administrator to make you a teacher."
          : e2.message
      );
      return;
    }

    router.push("/teach");
    router.refresh();
  }

  if (!courses.length) {
    return (
      <p className="small muted">
        There is no published course to open a class for yet. Ask the administrator to publish one.
      </p>
    );
  }

  return (
    <form onSubmit={submit}>
      <label className="fld" htmlFor="sc">Course</label>
      <select id="sc" value={courseId} onChange={(e) => setCourseId(e.target.value)}>
        {courses.map((c) => (
          <option key={c.id} value={c.id}>{c.title}</option>
        ))}
      </select>

      <label className="fld" htmlFor="sn">Section number</label>
      <input
        id="sn"
        required
        maxLength={40}
        value={number}
        onChange={(e) => setNumber(e.target.value)}
        placeholder="e.g. 201"
      />
      <p className="tiny muted" style={{ marginTop: 6 }}>
        Whatever your students see on their timetable. You set this, not them.
      </p>

      <label className="fld" htmlFor="st">Term</label>
      <input
        id="st"
        required
        maxLength={40}
        value={term}
        onChange={(e) => setTerm(e.target.value)}
        placeholder="e.g. Semester 1, 2026-27"
      />

      {error && <div className="err" style={{ marginTop: 12 }}>{error}</div>}

      <button className="btn gold block" style={{ marginTop: 16 }} disabled={busy}>
        {busy ? "Opening the class…" : "Open the class and get its link"}
      </button>
    </form>
  );
}
